# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
#sudo: false
sudo: required  # to allow r_binary_packages
cache: packages
env: _R_CHECK_FORCE_SUGGESTS_=false

# failures: Unable to locate package r-cran-dplyr
#r_binary_packages:
#  - dplyr
#  - purrr
#  - tibble
#  - minpack.lm
#  - segmented
#  - mlegp
#  - testthat
#  - knitr
